### ISSUE TITLE
[Milestone] Fix inconsistent space on both sides of grid layout recyclerview 

### ISSUE THREAD

**Issue by AkaneTan** [FoedusProgramme/Gramophone#110]
Should be 24 dp, but now it's something like 12

**Comment by VishnuSanal** [comment]
Hi, is this already being worked upon? If not, I'd like to work on this issue. I'm new here & looking forward to contributing. :)

**Comment by nift4** [comment]
It should be a fairly trivial fix, but it's a great chance to get familiar with the codebase, so feel free to send a PR

**Comment by VishnuSanal** [comment]
I can't build Gramophone on my local machine:

- first, I got file not found for missing `../package.properties` file.
- once I did a patch to fix that error by manually setting the `releaseType` variable,
- the project got built
- once I launched it on my device, it had package issues, since package name wasn't overridden.
- I overrode `applicationIdSuffix` and ran the app
- I got `StrictMode` policy violation incessantly
- Android won't even let me use my device!
- Assumed it was because of the package name, hence I rolled back the package name & tried again, only to result in infinite `StrictMode` policy violation dialog boxes.
- I tried a fix for this from Stack Overflow, but couldn't get to fix it.

are these issues only because of a missing `package.properties` file? am I missing something trivial or is this the way it is?!

**Comment by nift4** [comment]
I recently added StrictMode configured to a very harsh behaviour to find bugs.
You can either build release builds, fix the strictmode violations or change this to if (false):
https://github.com/AkaneTan/Gramophone/blob/beta/app/src/main/kotlin/org/akanework/gramophone/logic/GramophoneApplication.kt#L68
