### ISSUE TITLE
[FR] HQ media image directly from media file

### ISSUE THREAD

**Issue by wolf-yuan-6115** [FoedusProgramme/Gramophone#131]
**Is your feature request related to a problem? Please describe.**
Seems like the current method of getting album art or song artwork is by calling Android Media Store (idk I didn't check the code), is it possible to fetch it directly from the music file?

**Describe the solution you'd like**
Fetch song artwork from the file itself, not blurry Android Media Store one

**Describe alternatives you've considered**
I have no idea

**Comment by wolf-yuan-6115** [comment]
Follow up: Retro music player has implementation for this.

**Comment by nift4** [comment]
Where exactly are you seeing the bluriness?

Android loads audio thumbnails with half of the smaller screen edge, we only display larger thumbnails in notification and full player, so we can use ThumbnailUtils ourselves for a higher quality image.

**Comment by wolf-yuan-6115** [comment]
> Where exactly are you seeing the bluriness?
> 
> Android loads audio thumbnails with half of the smaller screen edge, we only display larger thumbnails in notification and full player, so we can use ThumbnailUtils ourselves for a higher quality image.

At the now playing screen.

In comparison, the first one is retro music with a higher image resolution toggle enabled, and the second one is the Gramophone one:

Retro music one is slightly better.

![Screenshot_20240311-175529.png](https://github.com/AkaneTan/Gramophone/assets/58245644/fb4b9be1-a249-4b2b-8c9f-a94216b76452)

![Screenshot_20240311-175517.png](https://github.com/AkaneTan/Gramophone/assets/58245644/7cce30f1-51fc-408a-85f0-c0d3882dff13)

Zoomed in version: (Two crops should be at the same size, again, first one is Retro Music, and second one is Gramophone):

![Screenshot_20240311-175529~2.png](https://github.com/AkaneTan/Gramophone/assets/58245644/ff51e6a8-1dac-4499-936e-11da068a557f)

![Screenshot_20240311-175517~2.png](https://github.com/AkaneTan/Gramophone/assets/58245644/45cd937e-127b-42e4-9262-33a3bb0499e2)

**Comment by AkaneTan** [comment]
Hi can you send example track and another player you've said so we can compare it?

**Comment by SnootyInk8302** [comment]
I came here to request the same feature.
Gramophone album art is noticeably lower resolution than Metro/Retro.
Here is an example:

Metro:
![Screenshot_20240419_020513_Metro](https://github.com/AkaneTan/Gramophone/assets/79272501/48fdfa2a-eed9-4bcd-a9a8-a45f4b11a72c)

Gramophone:
![Screenshot_20240419_020426_Gramophone](https://github.com/AkaneTan/Gramophone/assets/79272501/ce7edeac-66f6-4471-be86-d567146efad2)

Metro:
![Screenshot_20240419_020513_Metro_1](https://github.com/AkaneTan/Gramophone/assets/79272501/a8ce9f18-9775-4671-aeec-6d417610a790)

Gramophone:
![Screenshot_20240419_020426_Gramophone_1](https://github.com/AkaneTan/Gramophone/assets/79272501/eda16d95-bf5f-4b0e-b104-f32537489735)

The reason for that is because Metro/Retro has an option to Ignore Android Media Store and take the Cover that is directly embedded in the file itself.
Now, to be clear, in this example, the picture is 3000px which is absurdly high, so that might also be what's causing the issue.

**Comment by wolf-yuan-6115** [comment]
> I came here to request the same feature.
> Gramophone album art is noticeably lower resolution than Metro/Retro.
> Here is an example:
> 
> Metro:
> ![Screenshot_20240419_020513_Metro](https://github.com/AkaneTan/Gramophone/assets/79272501/48fdfa2a-eed9-4bcd-a9a8-a45f4b11a72c)
> 
> Gramophone:
> ![Screenshot_20240419_020426_Gramophone](https://github.com/AkaneTan/Gramophone/assets/79272501/ce7edeac-66f6-4471-be86-d567146efad2)
> 
> Metro:
> ![Screenshot_20240419_020513_Metro_1](https://github.com/AkaneTan/Gramophone/assets/79272501/a8ce9f18-9775-4671-aeec-6d417610a790)
> 
> Gramophone:
> ![Screenshot_20240419_020426_Gramophone_1](https://github.com/AkaneTan/Gramophone/assets/79272501/eda16d95-bf5f-4b0e-b104-f32537489735)
> 
> The reason for that is because Metro/Retro has an option to Ignore Android Media Store and take the Cover that is directly embedded in the file itself.
> Now, to be clear, in this example, the picture is 3000px which is absurdly high, so that might also be what's causing the issue.
> 

Additional info for those who don't know what Metro is, it's simply just a fork of Retro music.

**Comment by nift4** [comment]
Implemented this, will be in next release, a toggle called "Enhanced album cover loading" and requires photos permission for obvious reasons.

I guess the implementation details barely matter, but we now use MediaStore's cover generation (ThumbnailUtils) directly to get high quality covers while being consistent with MediaStore - hence it's not "Ignore MediaStore covers".

**Comment by SnootyInk8302** [comment]
Thank you very much for adding this option! I'm looking forward to the beta.
