### ISSUE TITLE
Please bring the old gramophone icon back

### ISSUE THREAD

**Issue by qumuq-til** [FoedusProgramme/Gramophone#159]
Please bring the old cream-colored icon back. It perfectly conveyed the old-school/minimalist convergence notion of the application all the while being different in a good way to stand out from the crowd, and the new icon is just a generic "Music Player HD" icon (fitting a "G" there doesn't make it better).

**Comment by nift4** [comment]
It's not a G, the it's a light blue disk and a dark blue combination of music note and the device's needle.
The old icon had a practical issue, namely that the Android 11+ playback resumption player displays the app icon in black/white only which looked very weird with the cream and brown colors.
Some people have also not recognized the old icon as Gramophone, but I guess that applies to the new one as well.

**Comment by Auxy6858** [comment]
Personally I also think the old icon was better, it made the app stand out more and was just better

**Comment by KirmesTVAustria** [comment]
I also think the old icon was better.

**Comment by rabaimorp** [comment]
I know it's supposed to be personal preference but I am on the same page. The old icon was great, the new one looks weird in my opinion.

**Comment by AkaneTan** [comment]
> and the new icon is just a generic "Music Player HD" icon (fitting a "G" there doesn't make it better).

Fun fact: Gramophone's ideology was to make something that fits into AOSP and acts as its default music player. But glad to see it has involved into something different. Will bring that icon back in next release.

**Comment by isaiahscape** [comment]
Real, the old icon is better

**Comment by nift4** [comment]
997d0ee

**Comment by Khazbs** [comment]
Oh no. I loved the new icon way way more than the old one. It was ingenious, because it looked like: (a) a head with headphones, (b) a note in a circle, (c) a vinyl record on a player — all at the same time. Also it fit perfectly among the default Google/Android app icons, which as a Google Pixel user and Material Design 3 enjoyer I appreciated a ton.

Some apps manage to offer customizable icons, exteraGram for example. Have you considered adding a setting that would allow to pick the preferred icon?

Still, it's a great thing that the source code is available, so anyone is free to fork, revert the change and build the app.

**Comment by Auxy6858** [comment]
I think a toggle would be cool, the white and blue felt very generic imo and didn't stand out much amongst other apps

**Comment by nift4** [comment]
Hi, please note that while everyone is free to discuss on closed issues, it's easily possible for the notification to get lost - if you desire a change, please create a feature request
