### ISSUE TITLE
Question: Regarding Float output quality

### ISSUE THREAD

**Issue by lamyergeier** [FoedusProgramme/Gramophone#246]
I know what is bit depth for a lossless file (example flac) 24-bit depth and 32 bit-depth. Could you please add a small note in README as what is the consequence of enabling and disabling this option? 

I have read somewhere that Android downsamples audio files to CD grade (44.1 kHz, 16 bit-depth), so is this option useful in playing HiFi grade audio files like (192 kHz, 32 bit-depth FLAC)? There are closed source apps like *HiByMusic Player* in the playstore, which does this. So by enabling this function can I avoid using the closed source app (as I am mainly interested in playing high quality audio)?

**Comment by nift4** [comment]
Float audio will give the audio stack 32-bit instead of 16-bit audio. The audio stack, as far as I know, however always configures USB devices at up to 96Khz audio quality only:
https://cs.android.com/android/platform/superproject/main/+/main:system/media/alsa_utils/alsa_device_profile.c;l=49?q=std_sample_rates

If you want bit perfect audio, your best bet is https://source.android.com/docs/core/audio/preferred-mixer-attr#bitperfect-attr-interface ; this feature is not implemented on any phone as far as I know, and Google's own ExoPlayer (the playback library we use) does not support it either ATM: https://github.com/androidx/media/issues/415
The proprietary apps directly access the USB devices using USB API and emulate the entire function of the audio stack and kernel to transmit audio directly. That is very annoying to implement (afaik there is no open source implementation), and as I do not think the difference actually matters all that much, and because Google announced a way forward (the bit perfect audio API) which will eventually have wider adoption, I do not plan to implement direct USB access.
