### ISSUE TITLE
[FR] Publish on a secure app store

### ISSUE THREAD

**Issue by ghost** [FoedusProgramme/Gramophone#283]
**TOFU and side-loading**
Currently the only way to obtain this app is through downloading the releases from GitHub or fdroid, in both cases, it is impossible to verify the validity of the app, as in one case an app store isn't used at all, and in the other one is used which has [significant security issues](https://privsec.dev/posts/android/f-droid-security-issues/). 

**the best solution**
Publish the app on GPlay, or [Accrescent](https://accrescent.app).

Both Verify the download and use certificate pinning, Accrescent additionally has strict requirements for permissions an app asks for.

However, Accrescent is currently in whitelist-only alpha, and probably not a good choice for now, it's better to wait until it's in beta or stable.

**quick and easy solution**
while this solution will be a lot worse in terms of security as compared to publishing on a secure App store, publishing the signing certificate hash independently from GitHub, for example on another website, or a social media post. Users then can use [AppVerifier](https://github.com/soupslurpr/AppVerifier) to ensure the validity of their app.

**Additional context**
Accrescent is mirrored in the [GrapheneOS](https://grapheneos.org) App store, a system App included with the AOSP-based OS, which employs additional hardening and is arguably the most secure OS currently available. 

Therefore, any app installed from Accrescent has a trust chain all the way to the OS signing keys. AppVerifer is available on there.

- [x] I will follow the issue format and will add `[FR]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
I'd not call Google Play particularily trustworthy. We're actually preparing for publishing there, and they forced us to give up our private signing key to them (well, I made a new one for Google Play because I did not want to give it up, but yeah).
F-Droid has reproducible builds enabled, and fdroiddata also has the signature: https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.akanework.gramophone.yml?ref_type=heads#L85
So you just need to verify the APK you're installing has that signature, as only the developers (and github CI, if you distrust them it's probably in your best interest to build the app yourself) have that private key, and you're good.

**Comment by ghost** [comment]
@nift4, I recommend you first read the article I linked, you don't seem to understand what my points are.

https://privsec.dev/posts/android/f-droid-security-issues/

As for distrusting GitHub, the reason is that your, or another contributor's account might be hacked, I hope you're using passkeys, but even if you are, there is a possibility of that happening, therefore the signing certificate hash *must* be published independently of the release. 

To be entirely clear, I understand that I have to trust the developer.

**Comment by nift4** [comment]
"The trusted party problem" - Gramophone is one of those apps published with reproducible builds and is developer-signed. There's no need to trust F-Droid as long as you verify the signature.

"Slow and irregular updates" - Gramophone, being part of the reproducible builds program, doesn't need to be signed on the airgapped server by the F-Droid team. As long as our builds are reproducible, they're published in ~1 week which is fine for regular feature updates 

"Low target API level (SDK) for client & apps" - Gramophone currently targets Android 14, and we'll update to 15 once I get my hands on a physical device running A15.

All that aside, if you don't want to use F-Droid, which of course is a matter of your free choice, the trusted signature hash can be obtained in two places:
1. https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/org.akanework.gramophone.yml?ref_type=heads#L85 - a repository on another platform where I don't have push access to
2. right here in this message: f451197ad7b80bd1bc981ba38a2c49d471856fb38bcc333676d6e8f8f3ce5d6e

As long as these two match, you can use any tool of your choice to verify the APK indeed has that signature. Once you installed the APK, thanks to Android's trust-on-first-install, you can install subsequent updates without worrying as Android will verify the same key is used to sign any future updates.

We are working on publishing on Google Play if you prefer that app store, however, that APK will have a different signature. Once the time comes, I am happy to provide the signature hash for the Google Play version as well.

Does this answer your question?

**Comment by b-risk** [comment]
Hello, I would like to add as I think this is the best FOSS local music player that it would be very good and the also the ideal to publish this on Accrescent for security reasons and that it also makes it easier for GrapheneOS users to install. I have personally moved away from using F-Droid and also trying to use Obtainium less, as well as the Play Store. After F-Droid's response to the sideloading news I think now is an even better time to have it there if possible.

**Comment by nift4** [comment]
Hello,

> publish this on Accrescent for security reasons

specifically? I currently do not see why it would be any better than F-Droid's reproducible build verification. In fact it seems to me they just promise to securely deliver the unmodified APK... at which point you can just get it from GitHub and verify the signature once (see README for reference).

> After F-Droid's response to the sideloading news

Did Accrescent publish any or are they just going to wait it out?

Also, Accrescent does not seem to be supported by fastlane which I use for uploading to app stores.

**Comment by b-risk** [comment]
> specifically? I currently do not see why it would be any better than F-Droid's reproducible build verification. In fact it seems to me they just promise to securely deliver the unmodified APK... at which point you can just get it from GitHub and verify the signature once (see README for reference).

It's more because the majority of apps on F-Droid do not use the system. The ideal would be to use a secure app store instead of relying on verifying signatures. 

> Did Accrescent publish any or are they just going to wait it out?

F-Droid is in a different situation because of their bad practices, I would read Graphene's statement on F-Droid's response: https://discuss.grapheneos.org/d/26966-f-droids-delevoper-statements-about-googles-registration/3

> Also, Accrescent does not seem to be supported by fastlane which I use for uploading to app stores.

Understandable if you decide not to I just would like it to be considered atleast, Accrescent is still very much in it's alpha stage. I think the more developers that come to Accrescent the more it will grow and become popular, which is why I was thinking of an opportunity for your app there as I saw that Auxio has recently started to upload theirs to it.

**Comment by nift4** [comment]
That rationale does make sense to me. There being no publishing tool (especially not fastlane which is one of the two big automations for this) or any kind of API is kind of sad though.

I also just saw https://accrescent.app/docs/guide/getting-started/new-app.html#domain-verification and while we used to own akanework.org when Gramophone first was released, that is no longer the case, so it seems it's not possible to publish our main track nor Play Store track apks because they both are `org.akanework.gramophone` and it'd need a new track with new package name, that then needs to be manually updated and screenshots & description to be manually uploaded as well. (It also doesn't seem to support l10n?)

Idk, maybe later when they have better tools for developers. I also personally think enforcing rDNS is unnecesarily strict as no app store does this. The only other platform I saw doing this was Maven Central which has a very different threat model (these names are exposed to users).

**Comment by b-risk** [comment]
> That rationale does make sense to me. There being no publishing tool (especially not fastlane which is one of the two big automations for this) or any kind of API is kind of sad though.

The way I see it is F-Droid has enough security concerns even though your app specifically might be doing everything it can, me having it for one app doesn't justify it for me. I would like Accrescent to become a standard as it's secure by default and makes the process easier (and is the main app store on GrapheneOS besides Play Store.) 

> Idk, maybe later when they have better tools for developers. I also personally think enforcing rDNS is unnecesarily strict as no app store does this. The only other platform I saw doing this was Maven Central which has a very different threat model (these names are exposed to users).

I respect your decision, I will add though that I'm no developer but if I understand correctly they may be doing this to try and avoid cases in which scammers will upload apps using package names or app IDs belonging to other organizations.
