### ISSUE TITLE
[BUG] DATE ID3 tag is being ignored

### ISSUE THREAD

**Issue by astatine** [FoedusProgramme/Gramophone#321]
**Describe the bug**
All the tracks in my library are being grouped under 'Unknown Year' in the Dates tab. All my tracks are `.opus`, I cannot currently check with other file formats.

**To Reproduce**
1. Open Gramophone
2. Go to the 'Dates' tab -- all tracks are grouped under 'Unknown year'
3. Go to the 'Details' for any track -- the Year tag says 'Unknown year'

**Expected behavior**
My tracks are grouped correctly according to their DATE ID3 tags

**Screenshots**
https://imgur.com/a/EN6wP4U
The first screenshot is of the 'Dates' tab and the second one is of the track 'Details'.

**Smartphone (please complete the following information):**
 - Device: Xiaomi phone
 - OS: Android 13.1 (custom ROM)
 - App Version: 1.0.15.64ab51 (f-droid build)

**Additional context**
Other music players like Phonograph Plus (from f-droid) read the DATE tag correctly.

- [x] I will open one issue per bug, follow the issue format and will add `[BUG]` to the start of my issue title, and I acknowledge that if I don't follow the format, my issue might get closed without further explanation.

**Comment by nift4** [comment]
Hi, please refer to: https://issuetracker.google.com/issues/158367283#comment6

**Comment by astatine** [comment]
@nift4 Hi, thanks for the quick response and the informative link. This sucks.

I was mistaken about Phonograph Plus; it shows a '-' for the YEAR/DATE (but the track 'tags' somehow show the year correctly). Also I learned that `.opus` and related don't use ID3 at all, but 'VorbisComments'.

Thanks again; feel free to close this issue.

**Comment by bohanubis** [comment]
so as I understand there is no way to fix this even if date is YYYY:MM:DD instead of (-)
if thats the case are you interested on me trying to implement a specific solution that doesn't use the problematic function
(I have no idea about android development but i might as well ask)

**Comment by nift4** [comment]
@beh-10257 The Android system provides access to a sqlite database that contains all media metadata, including date information. Gramophone uses said database. To fix it, you'd have to roll your own database or scanning system which is not trivial - the Android database scanner does enjoy some privilegies about being notified about file system changes we can't easily replicate.

**Comment by bohanubis** [comment]
@nift4 sorry for taking long
but is it a bad idea to use refresh button
to run a custom scanning system so gramaphone knows that wow this file is from 2017
and than it saves it to its internal database (does gramaphone have one ??)
and than only run that custom program either on new files that are opus files and at the same time not in the database
and everytime the user opens an opus file
or idk is there an api that can notify gramaphone that an opus file has changed
if such an api exists just run script to change date when files change or show up

and I can't imagine such a script or whatever will be such a toll on the system since well

![Image](https://github.com/user-attachments/assets/88fa7778-c633-42bd-995c-99fc63b54690)

and that command isn't even optimised to just pull the DATE tag so yeah
I'm gonna try working on this
just tell me what approach would be best

**Comment by nift4** [comment]
@beh-10257 I don't want to discourage you, in fact I think your idea is not bad at all (MediaStore doesn't support DATE for ID3v2.4, most formats in Vorbis comments, screws up file encoding hence sometimes results in encoding garbage as song title, does not expose audio format information; custom tagging supplementing would solve all that and more), and I have been thinking about doing something like that too, but I can think of some problems I/you should consider:
- regarding speed: my library of 1500 songs would need around 3,8 minutes if scanning takes as long as it does with ffprobe, I'd aim for 30 milliseconds per song at most
- though, I still think the loading should be done asynchronously (i.e. songs are loaded from MediaStore and additional tag information is supplemented later) because some storage chips are slow and some people have really large libraries, and loading times of 15 seconds are already deemed unacceptable by many people, which will be quite a lot of refactoring around all places of the app
- integrating ffmpeg for tagging will bloat app size (as we distribute on f-droid and github which don't really accomodate for split apks, and shipping ffmpeg for all four archs is probably a good 25mb on top, which is a compromise I don't really want), meanwhile media3 extractors are not optimized for mass-extraction and cause GC/heap trashing when used like that due to inefficient allocations, hence we would probably need some other implementation of tagging or optimizing media3
- there is no internal database atm, we need a database software such as SQLite or a DAO like Room
- there is no OS API to get information about file/folder changes while the app isn't running, so we have to scan the folder hierachy on each startup (asynchronously in the background) for file size and mtime changes and compare with the database
- if we create a database anyway, I'd like to atleast somewhat consider future features like: 1. playback history, 2. song ratings, 3. user playlists; all of those require tracking files across renames with some metric (maybe hash of tags/file, or file path, or musicbrainz track id tag, if only one of these changes we can track renames or tag edits, and otherwise we can still do best effort, but it also needs a conflict resolution UI)

I have reasonable doubts I will be able to work on all of that this year, tbh.

**Comment by bohanubis** [comment]
I'll try to help (I can't build the project because of whatever media3 is and tbh I low key love this project)
this is my first actual time developing in android and I'll be learning kotlin along the way so yeah
keep your hopes if any down
yeah integrating ffmpeg is stupid I could have shown you the same thing using opustags its just not installed now
and that project is less than 1 mb large as far as I remember
about the database we can use https://acoustid.org/
since well they use at a commercial scale I bet it will work on whatever we are doing
I would love to add listenbrainz and neodb integration myself so yeah
writing our own code will be easier than using another library
I don't really know if thats viable since all the code that I see doing this stuff is written in C and this is in kotlin so yeah

**Comment by nift4** [comment]
@beh-10257 are you Bkkk on telegram? if so we can talk there
anyway it should build now: 652fc7237540849ae919ee455451bfd479f30350
for the database, we don't need one to find tags based on content, that's music tagger's job
we need something to map file path to cached extracted tags to cut down on loading time
so we can use any normal database software like Room
for how to read tags, you _could_ check how opus (and others) are done in media3: https://github.com/nift4/media/blob/gramophone/libraries/extractor/src/main/java/androidx/media3/extractor/ogg/OggExtractor.java
please also note that we need not only vorbis comments (ogg/flac) but id3 (mp3) and whatever mp4 uses as well to cover common tagging systems (there are bugs in extraction of all of those formats)
and about listenbrainz, one of the policies of this project is that there is no internet permission, which means you would need to implement that as a plugin (for example using AIDL) that can access the internet, but I'd be happy to accept such a plugin system from Gramophone's side and am willing to do the implementing on the Gramophone side if you do the plugin side; I'm not sure what neodb is for but similar concerns likely apply

**Comment by bohanubis** [comment]
sorry wasn't clear about the database part
I mean to use the library they are using
aka
https://acoustid.org/chromaprint
so everyfile even after renaming will have a unique fingerprint (ideally)
so we can track stuff even after moving copying duplication whatever
so we map the fingerprint to tags and listening times and ratings and stuff
